<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Apêndice B — Ciência aberta e reprodutibilidade – Revisão sistemática de ponta a ponta</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../metodo/apendice-c-glossario.html" rel="next">
<link href="../metodo/apendice-a-leituras.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c7ef8655bab0e55525918e061bda609f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../metodo/apendice-a-leituras.html">Apêndices</a></li><li class="breadcrumb-item"><a href="../metodo/apendice-b-reprodutibilidade.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Ciência aberta e reprodutibilidade</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Revisão sistemática de ponta a ponta</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Compartilhar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Compartilhar"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apresentação</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/01-fundamentos-tipos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Fundamentos e família de revisões</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/02-pergunta-teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Pergunta de pesquisa, teoria do programa e frameworks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/03-protocolo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Protocolo, pré-registro e emendas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/04-busca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Busca da literatura</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/05-organizacao-triagem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Organização dos registros, deduplicação e triagem</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/06-qualidade-risco-vies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Qualidade dos estudos e risco de viés</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/07-decomposicao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Decomposição dos estudos (extração de dados)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/08a-sintese-quantitativa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Síntese quantitativa: meta-análise, síntese sem meta-análise e testes combinados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/08b-sintese-qualitativa-integracao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Síntese qualitativa, realista, QCA e integração mista sequencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/09-certeza-evidencia-pratica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Certeza da evidência e da evidência à prática</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/10-relato-divulgacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Relato e divulgação: PRISMA, formato OQF e tradução do conhecimento</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/11-ia-na-revisao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Inteligência artificial na revisão sistemática: usos, riscos e validação</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/apendice-a-leituras.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Leituras comentadas por etapa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/apendice-b-reprodutibilidade.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Ciência aberta e reprodutibilidade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/apendice-c-glossario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Glossário</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../metodo/apendice-d-especificacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Especificação metodológica desta base</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#sec-apb-regras" id="toc-sec-apb-regras" class="nav-link active" data-scroll-target="#sec-apb-regras"><span class="header-section-number">B.1</span> Regras mínimas</a></li>
  <li><a href="#sec-apb-estrutura" id="toc-sec-apb-estrutura" class="nav-link" data-scroll-target="#sec-apb-estrutura"><span class="header-section-number">B.2</span> Estrutura do projeto e versionamento</a></li>
  <li><a href="#sec-apb-log" id="toc-sec-apb-log" class="nav-link" data-scroll-target="#sec-apb-log"><span class="header-section-number">B.3</span> Logs de decisão</a></li>
  <li><a href="#sec-apb-pacote" id="toc-sec-apb-pacote" class="nav-link" data-scroll-target="#sec-apb-pacote"><span class="header-section-number">B.4</span> O pacote aberto</a></li>
  <li><a href="#sec-apb-licencas" id="toc-sec-apb-licencas" class="nav-link" data-scroll-target="#sec-apb-licencas"><span class="header-section-number">B.5</span> Licenças e terceiros</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../metodo/apendice-a-leituras.html">Apêndices</a></li><li class="breadcrumb-item"><a href="../metodo/apendice-b-reprodutibilidade.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Ciência aberta e reprodutibilidade</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-reprodutibilidade" class="quarto-section-identifier">Apêndice B — Ciência aberta e reprodutibilidade</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Uma revisão é reprodutível quando outra pessoa, com os materiais publicados, consegue refazer a busca, chegar às mesmas contagens do fluxograma, reconstruir cada decisão de inclusão, reextrair os efeitos e rodar a análise até os mesmos números e rótulos. O PRISMA 2020 transforma essa exigência em itens de relato: registro e protocolo (24a e 24b), emendas (24c) e disponibilidade de formulários, dados extraídos, dados analisados, código e outros materiais (27) <span class="citation" data-cites="page2021prisma">(<a href="#ref-page2021prisma" role="doc-biblioref">Page, McKenzie, et al. 2021</a>)</span>. Este apêndice reúne as regras operacionais que os capítulos distribuem entre protocolo, busca, triagem, IA e relato. O que entra no pacote aberto, arquivo por arquivo, está na <a href="10-relato-divulgacao.html#sec-10-passos" class="quarto-xref"><span>Seção 11.5</span></a>; o texto de relato, na <a href="10-relato-divulgacao.html#sec-10-relato" class="quarto-xref"><span>Seção 11.10</span></a>.</p>
<section id="sec-apb-regras" class="level2" data-number="B.1">
<h2 data-number="B.1" class="anchored" data-anchor-id="sec-apb-regras"><span class="header-section-number">B.1</span> Regras mínimas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>O quê</th>
<th>Regra</th>
<th>Fonte</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Registro</td>
<td>Registrar o protocolo antes da triagem formal e declarar a etapa em que a revisão estava; em ciências sociais, OSF Registries com o formulário geral de revisão sistemática</td>
<td><span class="citation" data-cites="vandenakker2023increasing">Akker et al. (<a href="#ref-vandenakker2023increasing" role="doc-biblioref">2023, GSRRF–7</a>)</span>; <a href="03-protocolo.html#sec-03-registro" class="quarto-xref"><span>Seção 3.3</span></a></td>
</tr>
<tr class="even">
<td>Mudanças no registro</td>
<td>Registro submetido não se edita; mudanças entram como <em>update</em>, com justificativa, e o registro pode ficar sob embargo por até quatro anos</td>
<td><span class="citation" data-cites="cos2026registration">Center for Open Science (<a href="#ref-cos2026registration" role="doc-biblioref">2026</a>)</span></td>
</tr>
<tr class="odd">
<td>Emendas</td>
<td>Toda emenda é datada e rastreada, e o relato informa a mudança, o motivo e a etapa em que ocorreu</td>
<td><span class="citation" data-cites="moher2015prismap">Moher et al. (<a href="#ref-moher2015prismap" role="doc-biblioref">2015</a>, tabela 3)</span>; <span class="citation" data-cites="page2021explanation">Page, Moher, et al. (<a href="#ref-page2021explanation" role="doc-biblioref">2021</a>, item 24c)</span></td>
</tr>
<tr class="even">
<td>Estratégias de busca</td>
<td>Publicar as strings exatamente como foram rodadas, com data da última busca e total por fonte</td>
<td><span class="citation" data-cites="rethlefsen2021prismas">Rethlefsen et al. (<a href="#ref-rethlefsen2021prismas" role="doc-biblioref">2021</a>, itens 8, 13 e 15)</span></td>
</tr>
<tr class="odd">
<td>Decisões de seleção</td>
<td>Documentar a decisão sobre todos os registros; listas de incluídos e excluídos por estudo</td>
<td><span class="citation" data-cites="lefebvre2025searching">Lefebvre et al. (<a href="#ref-lefebvre2025searching" role="doc-biblioref">2025</a>, MECIR C41)</span>; <a href="05-organizacao-triagem.html#sec-05-regras" class="quarto-xref"><span>Seção 5.1</span></a></td>
</tr>
<tr class="even">
<td>Prompts e modelos</td>
<td>Registrar texto integral do prompt e versão do modelo; versões novas em arquivo novo, saídas nunca sobrescritas</td>
<td><span class="citation" data-cites="thomas2026raise3"><span class="nocase">Thomas et al.</span> (<a href="#ref-thomas2026raise3" role="doc-biblioref">2026, 19</a>)</span>; <a href="11-ia-na-revisao.html#sec-11-prompts" class="quarto-xref"><span>Seção 12.7</span></a></td>
</tr>
<tr class="odd">
<td>Dados e código</td>
<td>Dizer quais materiais estão públicos e onde; bases limpas em formato reutilizável (CSV), dicionário de variáveis, README e código</td>
<td><span class="citation" data-cites="page2021prisma">Page, McKenzie, et al. (<a href="#ref-page2021prisma" role="doc-biblioref">2021</a>, item 27)</span>; <span class="citation" data-cites="page2021explanation">Page, Moher, et al. (<a href="#ref-page2021explanation" role="doc-biblioref">2021</a>, item 27)</span></td>
</tr>
<tr class="even">
<td>Repositório</td>
<td>Material suplementar em repositório aberto e permanente, com link no relatório; a Campbell incentiva o compartilhamento segundo os princípios FAIR</td>
<td><span class="citation" data-cites="page2021explanation">Page, Moher, et al. (<a href="#ref-page2021explanation" role="doc-biblioref">2021</a>)</span>; <span class="citation" data-cites="campbell2021policies">The Campbell Collaboration (<a href="#ref-campbell2021policies" role="doc-biblioref">2021, 19–20</a>)</span></td>
</tr>
<tr class="odd">
<td>Ausência</td>
<td>Revisão sem registro, sem protocolo ou sem dados públicos diz isso nos itens correspondentes</td>
<td><span class="citation" data-cites="page2021prisma">Page, McKenzie, et al. (<a href="#ref-page2021prisma" role="doc-biblioref">2021</a>, itens 24-27)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="sec-apb-estrutura" class="level2" data-number="B.2">
<h2 data-number="B.2" class="anchored" data-anchor-id="sec-apb-estrutura"><span class="header-section-number">B.2</span> Estrutura do projeto e versionamento</h2>
<p>A reprodução começa pela organização das pastas. A skill <code>revisao-sistematica</code> cria um projeto com uma pasta por etapa e arquivos de estado na raiz (<a href="apendice-d-especificacao.html#sec-especificacao-contrato" class="quarto-xref"><span>Seção D.5</span></a>):</p>
<pre class="text"><code>00-protocolo/      protocolo vN, emendas, codebook v0, plano de IA
01-busca/brutos/   exportações das bases, sem edição
01-busca/strings/  versões das strings e do conjunto de estudos-âncora
02-triagem/        lotes, prompts/vN.md, validação
03-textos/pdfs/    textos completos (não vão para o pacote público)
04-qualidade/      julgamentos de risco de viés por domínio
05-decomposicao/   codebook, fichas, base extraída
06-analise/        tabela de efeitos, código R, saídas
07-relatorio/      relatório, fluxograma, checklists, declaração de IA
dados/             registros.csv, registros_unicos.csv, decisoes.jsonl
rs_estado.json     versões ativas e artefatos congelados (caminho, SHA-256, data)
rs_log.jsonl       histórico de eventos, só acréscimo</code></pre>
<p>Quatro regras de versionamento tornam a estrutura auditável:</p>
<ol type="1">
<li><strong>Bruto é intocável.</strong> Exportações das bases ficam como vieram, com <em>hash</em>; toda limpeza acontece em arquivo derivado (<a href="05-organizacao-triagem.html#sec-05-esquema" class="quarto-xref"><span>Seção 5.2</span></a>).</li>
<li><strong>Congelar é registrar.</strong> Protocolo, critérios de triagem, prompts, codebook e filtros ganham versão (vN) e <em>hash</em> quando aprovados; a mudança seguinte gera vN+1 e um evento de emenda, e as decisões tomadas com a versão anterior continuam associadas a ela (<a href="03-protocolo.html#sec-03-registro" class="quarto-xref"><span>Seção 3.3</span></a>).</li>
<li><strong>Prompt é instrumento de medição.</strong> <code>prompts/vN.md</code> guarda metadados, texto integral e <em>hash</em>; o modelo exato e os parâmetros vão junto; o prompt usado na validação é o mesmo da rodada completa (<a href="11-ia-na-revisao.html#sec-11-prompts" class="quarto-xref"><span>Seção 12.7</span></a>).</li>
<li><strong>Contagens não se digitam.</strong> O fluxograma sai das tabelas de decisões, com somas conferidas; se não fecha, não é gerado (<a href="05-organizacao-triagem.html#sec-05-prisma" class="quarto-xref"><span>Seção 5.5</span></a>).</li>
</ol>
</section>
<section id="sec-apb-log" class="level2" data-number="B.3">
<h2 data-number="B.3" class="anchored" data-anchor-id="sec-apb-log"><span class="header-section-number">B.3</span> Logs de decisão</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Log</th>
<th>Campos mínimos</th>
<th>Onde é detalhado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Buscas</td>
<td>Identificador, fonte e interface, string (versão), data de execução, filtros aplicados na base, número bruto, arquivo e <em>hash</em></td>
<td><a href="04-busca.html#sec-04-skill" class="quarto-xref"><span>Seção 4.11</span></a></td>
</tr>
<tr class="even">
<td>Emendas e desvios</td>
<td>Data, versão anterior e nova, o que mudou, motivo, etapa em que a revisão estava, decisões afetadas</td>
<td><a href="03-protocolo.html#sec-03-registro" class="quarto-xref"><span>Seção 3.3</span></a></td>
</tr>
<tr class="odd">
<td>Decisões de triagem</td>
<td><code>id_rs</code>, etapa, rodada, revisor e tipo de ator (humano, subagente, API, <em>script</em>), modelo e <em>hash</em> do prompt, decisão (incluir, excluir, incerto), critério que falhou, justificativa, trecho, lote, horário, correção e motivo</td>
<td><a href="05-organizacao-triagem.html#sec-05-skill" class="quarto-xref"><span>Seção 5.12</span></a></td>
</tr>
<tr class="even">
<td>Extração e risco de viés</td>
<td>Valor, trecho literal e página; fórmula de conversão; julgamento por domínio com justificativa; quem codificou e quem conferiu</td>
<td><a href="07-decomposicao.html#sec-07-regras" class="quarto-xref"><span>Seção 7.1</span></a>; <a href="06-qualidade-risco-vies.html#sec-06-regras" class="quarto-xref"><span>Seção 6.1</span></a></td>
</tr>
<tr class="odd">
<td>Uso de IA</td>
<td>Ferramenta, modelo, versão, datas, parâmetros, papel por etapa, validação com intervalos, elusão, estabilidade e custo</td>
<td><a href="11-ia-na-revisao.html#sec-11-relato" class="quarto-xref"><span>Seção 12.15</span></a></td>
</tr>
</tbody>
</table>
<p>O log de desvios responde a uma pergunta que o leitor sempre faz: o que foi decidido depois de ver os dados? Uma mudança planejada como contingência no protocolo só precisa ser registrada como acionada; as demais entram como emenda justificada <span class="citation" data-cites="vandenakker2023increasing">(<a href="#ref-vandenakker2023increasing" role="doc-biblioref">Akker et al. 2023</a>)</span>.</p>
</section>
<section id="sec-apb-pacote" class="level2" data-number="B.4">
<h2 data-number="B.4" class="anchored" data-anchor-id="sec-apb-pacote"><span class="header-section-number">B.4</span> O pacote aberto</h2>
<p>A lista de arquivos do pacote, com o item PRISMA de cada um, está na <a href="10-relato-divulgacao.html#sec-10-passos" class="quarto-xref"><span>Seção 11.5</span></a>. Antes de depositar, confira:</p>
<ol type="1">
<li><strong>README</strong> descreve cada arquivo, a versão da revisão e a ordem para reproduzir, do arquivo de registros ao relatório.</li>
<li><strong>Fluxograma reproduzível</strong>: as contagens publicadas saem das tabelas de registros e decisões incluídas no pacote.</li>
<li><strong>Código roda do zero</strong> num ambiente limpo, com as versões dos pacotes usados na análise registradas junto dos <em>scripts</em> (<a href="10-relato-divulgacao.html#sec-10-passos" class="quarto-xref"><span>Seção 11.5</span></a>); quem usa programas de apontar e clicar descreve todos os passos <span class="citation" data-cites="page2021explanation">(<a href="#ref-page2021explanation" role="doc-biblioref">Page, Moher, et al. 2021</a>, item 27)</span>.</li>
<li><strong>Tabela de conversões</strong> acompanha os dados extraídos, com fórmula e pressupostos de cada efeito convertido (<a href="07-decomposicao.html#sec-07-efeitos" class="quarto-xref"><span>Seção 7.4</span></a>).</li>
<li><strong>Tabela-fonte da caixa de ferramentas</strong> e a versão da regra de rótulos permitem refazer cada rótulo (<a href="10-relato-divulgacao.html#sec-10-painel" class="quarto-xref"><span>Seção 11.3</span></a>).</li>
<li><strong>Prompts, saídas brutas e métricas de validação</strong> estão presentes quando houve uso de IA (<a href="11-ia-na-revisao.html#sec-11-relato" class="quarto-xref"><span>Seção 12.15</span></a>).</li>
<li><strong>Material protegido fica de fora</strong>: exportações de bases bibliográficas costumam conter conteúdo licenciado, e as licenças devem ser lidas antes de compartilhar; no lugar dos resumos, publique identificadores e decisões <span class="citation" data-cites="page2021explanation">(<a href="#ref-page2021explanation" role="doc-biblioref">Page, Moher, et al. 2021</a>, item 27)</span>. PDFs dos estudos não entram no pacote.</li>
<li><strong>Dados pessoais</strong> (de autores contatados, de participantes de validação) são removidos ou tratados conforme a LGPD <span class="citation" data-cites="brasil2018lgpd">(<a href="#ref-brasil2018lgpd" role="doc-biblioref">Brasil 2018</a>)</span>.</li>
<li><strong>Identificador persistente</strong> do depósito aparece no artigo, na síntese de evidências e em cada produto derivado (<a href="10-relato-divulgacao.html#sec-10-passos" class="quarto-xref"><span>Seção 11.5</span></a>).</li>
</ol>
</section>
<section id="sec-apb-licencas" class="level2" data-number="B.5">
<h2 data-number="B.5" class="anchored" data-anchor-id="sec-apb-licencas"><span class="header-section-number">B.5</span> Licenças e terceiros</h2>
<p>Três situações exigem cuidado. A primeira são os dados de terceiros: resumos e registros exportados de bases comerciais seguem a licença da base, não a da revisão <span class="citation" data-cites="page2021explanation">(<a href="#ref-page2021explanation" role="doc-biblioref">Page, Moher, et al. 2021</a>, item 27)</span>. A segunda é o envio de títulos, resumos e PDFs a provedores de IA: os termos de serviço podem permitir o uso para treino, e carregar texto protegido pode constituir reprodução, por isso os acordos de processamento e de confidencialidade são conferidos antes do uso e relatados <span class="citation" data-cites="thomas2026raise3 holst2025prismatraice">(<a href="#ref-thomas2026raise3" role="doc-biblioref"><span class="nocase">Thomas et al.</span> 2026, 29</a>; <a href="#ref-holst2025prismatraice" role="doc-biblioref">Holst et al. 2025</a>)</span>. A terceira é o material próprio da revisão (codebook, dados extraídos, código, tabela de achados): declare uma licença explícita no README de cada componente. A skill <code>revisao-sistematica</code> adota MIT para o código e CC BY 4.0 para textos, modelos e codebooks (<a href="apendice-d-especificacao.html#sec-especificacao-contrato" class="quarto-xref"><span>Seção D.5</span></a>). Para reutilizar materiais didáticos do MAPE/IESP-UERJ ou modelos de terceiros, como o fluxograma PRISMA, siga a licença e a atribuição indicadas pela fonte <span class="citation" data-cites="prisma2020flow">(<a href="#ref-prisma2020flow" role="doc-biblioref">PRISMA 2021</a>)</span>.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-vandenakker2023increasing" class="csl-entry" role="listitem">
Akker, Olmo R. van den, Gjalt-Jorn Ygram Peters, Caitlin J. Bakker, et al. 2023. <span>“Increasing the transparency of systematic reviews: presenting a generalized registration form”</span>. <em>Systematic Reviews</em> 12: 170. <a href="https://doi.org/10.1186/s13643-023-02281-7">https://doi.org/10.1186/s13643-023-02281-7</a>.
</div>
<div id="ref-brasil2018lgpd" class="csl-entry" role="listitem">
Brasil. 2018. <em>Lei n<span></span> 13.709, de 14 de agosto de 2018: Lei Geral de Prote<span>ç</span><span>ã</span>o de Dados Pessoais (<span>LGPD</span>)</em>. Di<span>á</span>rio Oficial da Uni<span>ã</span>o. <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm">https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm</a>.
</div>
<div id="ref-cos2026registration" class="csl-entry" role="listitem">
Center for Open Science. 2026. <em>Welcome to Registrations &amp; Preregistrations!</em> OSF Support. <a href="https://help.osf.io/article/330-welcome-to-registrations">https://help.osf.io/article/330-welcome-to-registrations</a>.
</div>
<div id="ref-holst2025prismatraice" class="csl-entry" role="listitem">
Holst, Dirk, Keno Moenck, Julian Koch, Ole Schmedemann, e Thorsten Schüppstuhl. 2025. <span>“Transparent Reporting of <span>AI</span> in Systematic Literature Reviews: Development of the <span>PRISMA-trAIce</span> Checklist”</span>. <em>JMIR AI</em> 4: e80247. <a href="https://doi.org/10.2196/80247">https://doi.org/10.2196/80247</a>.
</div>
<div id="ref-lefebvre2025searching" class="csl-entry" role="listitem">
Lefebvre, Carol, Julie Glanville, Simon Briscoe, et al. 2025. <span>“Chapter 4: Searching for and selecting studies”</span>. Em <em>Cochrane Handbook for Systematic Reviews of Interventions</em>, version 6.5.1, organizado por Julian P. T. Higgins, James Thomas, Jacqueline Chandler, et al. Cochrane. <a href="https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current/chapter-04">https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current/chapter-04</a>.
</div>
<div id="ref-moher2015prismap" class="csl-entry" role="listitem">
Moher, David, Larissa Shamseer, Mike Clarke, et al. 2015. <span>“Preferred reporting items for systematic review and meta-analysis protocols (<span>PRISMA-P</span>) 2015 statement”</span>. <em>Systematic Reviews</em> 4 (1): 1. <a href="https://doi.org/10.1186/2046-4053-4-1">https://doi.org/10.1186/2046-4053-4-1</a>.
</div>
<div id="ref-page2021prisma" class="csl-entry" role="listitem">
Page, Matthew J., Joanne E. McKenzie, Patrick M. Bossuyt, et al. 2021. <span>“The <span>PRISMA</span> 2020 statement: an updated guideline for reporting systematic reviews”</span>. <em>BMJ</em> 372: n71. <a href="https://doi.org/10.1136/bmj.n71">https://doi.org/10.1136/bmj.n71</a>.
</div>
<div id="ref-page2021explanation" class="csl-entry" role="listitem">
Page, Matthew J., David Moher, Patrick M. Bossuyt, et al. 2021. <span>“<span>PRISMA</span> 2020 explanation and elaboration: updated guidance and exemplars for reporting systematic reviews”</span>. <em>BMJ</em> 372: n160. <a href="https://doi.org/10.1136/bmj.n160">https://doi.org/10.1136/bmj.n160</a>.
</div>
<div id="ref-prisma2020flow" class="csl-entry" role="listitem">
PRISMA. 2021. <em><span>PRISMA</span> 2020 flow diagram</em>. PRISMA Statement website. <a href="https://www.prisma-statement.org/prisma-2020-flow-diagram">https://www.prisma-statement.org/prisma-2020-flow-diagram</a>.
</div>
<div id="ref-rethlefsen2021prismas" class="csl-entry" role="listitem">
Rethlefsen, Melissa L., Shona Kirtley, Siw Waffenschmidt, et al. 2021. <span>“<span>PRISMA-S</span>: an extension to the <span>PRISMA</span> Statement for Reporting Literature Searches in Systematic Reviews”</span>. <em>Systematic Reviews</em> 10 (1): 39. <a href="https://doi.org/10.1186/s13643-020-01542-z">https://doi.org/10.1186/s13643-020-01542-z</a>.
</div>
<div id="ref-campbell2021policies" class="csl-entry" role="listitem">
The Campbell Collaboration. 2021. <em>Campbell systematic reviews: policies and guidelines</em>. Campbell Policies and Guidelines. The Campbell Collaboration. <a href="https://www.campbellcollaboration.org/wp-content/uploads/2024/11/Campbell-Policies-and-Guidelines-_May3-2022.docx.pdf">https://www.campbellcollaboration.org/wp-content/uploads/2024/11/Campbell-Policies-and-Guidelines-_May3-2022.docx.pdf</a>.
</div>
<div id="ref-thomas2026raise3" class="csl-entry" role="listitem">
<span class="nocase">Thomas, James, Kaitlyn Hair, Anna Noel-Storr, et al.</span> 2026. <em>Responsible use of <span>AI</span> in evidence <span>SynthEsis</span> (<span>RAISE</span>) 3: selecting and using <span>AI</span> evidence synthesis tools</em>. Open Science Framework, rascunho, vers<span>ã</span>o 3.1 (13 mar. 2026). <a href="https://doi.org/10.17605/OSF.IO/FWAUD">https://doi.org/10.17605/OSF.IO/FWAUD</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../metodo/apendice-a-leituras.html" class="pagination-link" aria-label="Leituras comentadas por etapa">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Leituras comentadas por etapa</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../metodo/apendice-c-glossario.html" class="pagination-link" aria-label="Glossário">
        <span class="nav-page-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Glossário</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Ciência aberta e reprodutibilidade {#sec-reprodutibilidade}</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Uma revisão é reprodutível quando outra pessoa, com os materiais publicados, consegue refazer a busca, chegar às mesmas contagens do fluxograma, reconstruir cada decisão de inclusão, reextrair os efeitos e rodar a análise até os mesmos números e rótulos. O PRISMA 2020 transforma essa exigência em itens de relato: registro e protocolo (24a e 24b), emendas (24c) e disponibilidade de formulários, dados extraídos, dados analisados, código e outros materiais (27) <span class="co">[</span><span class="ot">@page2021prisma</span><span class="co">]</span>. Este apêndice reúne as regras operacionais que os capítulos distribuem entre protocolo, busca, triagem, IA e relato. O que entra no pacote aberto, arquivo por arquivo, está na @sec-10-passos; o texto de relato, na @sec-10-relato.</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## Regras mínimas {#sec-apb-regras}</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> O quê <span class="pp">|</span> Regra <span class="pp">|</span> Fonte <span class="pp">|</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Registro <span class="pp">|</span> Registrar o protocolo antes da triagem formal e declarar a etapa em que a revisão estava; em ciências sociais, OSF Registries com o formulário geral de revisão sistemática <span class="pp">|</span> @vandenakker2023increasing <span class="co">[</span><span class="ot">GSRRF-7</span><span class="co">]</span>; @sec-03-registro <span class="pp">|</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mudanças no registro <span class="pp">|</span> Registro submetido não se edita; mudanças entram como *update*, com justificativa, e o registro pode ficar sob embargo por até quatro anos <span class="pp">|</span> @cos2026registration <span class="pp">|</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Emendas <span class="pp">|</span> Toda emenda é datada e rastreada, e o relato informa a mudança, o motivo e a etapa em que ocorreu <span class="pp">|</span> @moher2015prismap <span class="co">[</span><span class="ot">tabela 3</span><span class="co">]</span>; @page2021explanation <span class="co">[</span><span class="ot">item 24c</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Estratégias de busca <span class="pp">|</span> Publicar as strings exatamente como foram rodadas, com data da última busca e total por fonte <span class="pp">|</span> @rethlefsen2021prismas <span class="co">[</span><span class="ot">itens 8, 13 e 15</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Decisões de seleção <span class="pp">|</span> Documentar a decisão sobre todos os registros; listas de incluídos e excluídos por estudo <span class="pp">|</span> @lefebvre2025searching <span class="co">[</span><span class="ot">MECIR C41</span><span class="co">]</span>; @sec-05-regras <span class="pp">|</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Prompts e modelos <span class="pp">|</span> Registrar texto integral do prompt e versão do modelo; versões novas em arquivo novo, saídas nunca sobrescritas <span class="pp">|</span> @thomas2026raise3 <span class="co">[</span><span class="ot">p. 19</span><span class="co">]</span>; @sec-11-prompts <span class="pp">|</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Dados e código <span class="pp">|</span> Dizer quais materiais estão públicos e onde; bases limpas em formato reutilizável (CSV), dicionário de variáveis, README e código <span class="pp">|</span> @page2021prisma <span class="co">[</span><span class="ot">item 27</span><span class="co">]</span>; @page2021explanation <span class="co">[</span><span class="ot">item 27</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Repositório <span class="pp">|</span> Material suplementar em repositório aberto e permanente, com link no relatório; a Campbell incentiva o compartilhamento segundo os princípios FAIR <span class="pp">|</span> @page2021explanation; @campbell2021policies <span class="co">[</span><span class="ot">p. 19-20</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Ausência <span class="pp">|</span> Revisão sem registro, sem protocolo ou sem dados públicos diz isso nos itens correspondentes <span class="pp">|</span> @page2021prisma <span class="co">[</span><span class="ot">itens 24-27</span><span class="co">]</span> <span class="pp">|</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## Estrutura do projeto e versionamento {#sec-apb-estrutura}</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>A reprodução começa pela organização das pastas. A skill <span class="in">`revisao-sistematica`</span> cria um projeto com uma pasta por etapa e arquivos de estado na raiz (@sec-especificacao-contrato):</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="in">00-protocolo/      protocolo vN, emendas, codebook v0, plano de IA</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="in">01-busca/brutos/   exportações das bases, sem edição</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="in">01-busca/strings/  versões das strings e do conjunto de estudos-âncora</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="in">02-triagem/        lotes, prompts/vN.md, validação</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="in">03-textos/pdfs/    textos completos (não vão para o pacote público)</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="in">04-qualidade/      julgamentos de risco de viés por domínio</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="in">05-decomposicao/   codebook, fichas, base extraída</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="in">06-analise/        tabela de efeitos, código R, saídas</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="in">07-relatorio/      relatório, fluxograma, checklists, declaração de IA</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="in">dados/             registros.csv, registros_unicos.csv, decisoes.jsonl</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="in">rs_estado.json     versões ativas e artefatos congelados (caminho, SHA-256, data)</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="in">rs_log.jsonl       histórico de eventos, só acréscimo</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>Quatro regras de versionamento tornam a estrutura auditável:</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Bruto é intocável.** Exportações das bases ficam como vieram, com *hash*; toda limpeza acontece em arquivo derivado (@sec-05-esquema).</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Congelar é registrar.** Protocolo, critérios de triagem, prompts, codebook e filtros ganham versão (vN) e *hash* quando aprovados; a mudança seguinte gera vN+1 e um evento de emenda, e as decisões tomadas com a versão anterior continuam associadas a ela (@sec-03-registro).</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Prompt é instrumento de medição.** <span class="in">`prompts/vN.md`</span> guarda metadados, texto integral e *hash*; o modelo exato e os parâmetros vão junto; o prompt usado na validação é o mesmo da rodada completa (@sec-11-prompts).</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Contagens não se digitam.** O fluxograma sai das tabelas de decisões, com somas conferidas; se não fecha, não é gerado (@sec-05-prisma).</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## Logs de decisão {#sec-apb-log}</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Log <span class="pp">|</span> Campos mínimos <span class="pp">|</span> Onde é detalhado <span class="pp">|</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Buscas <span class="pp">|</span> Identificador, fonte e interface, string (versão), data de execução, filtros aplicados na base, número bruto, arquivo e *hash* <span class="pp">|</span> @sec-04-skill <span class="pp">|</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Emendas e desvios <span class="pp">|</span> Data, versão anterior e nova, o que mudou, motivo, etapa em que a revisão estava, decisões afetadas <span class="pp">|</span> @sec-03-registro <span class="pp">|</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Decisões de triagem <span class="pp">|</span> <span class="in">`id_rs`</span>, etapa, rodada, revisor e tipo de ator (humano, subagente, API, *script*), modelo e *hash* do prompt, decisão (incluir, excluir, incerto), critério que falhou, justificativa, trecho, lote, horário, correção e motivo <span class="pp">|</span> @sec-05-skill <span class="pp">|</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Extração e risco de viés <span class="pp">|</span> Valor, trecho literal e página; fórmula de conversão; julgamento por domínio com justificativa; quem codificou e quem conferiu <span class="pp">|</span> @sec-07-regras; @sec-06-regras <span class="pp">|</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Uso de IA <span class="pp">|</span> Ferramenta, modelo, versão, datas, parâmetros, papel por etapa, validação com intervalos, elusão, estabilidade e custo <span class="pp">|</span> @sec-11-relato <span class="pp">|</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>O log de desvios responde a uma pergunta que o leitor sempre faz: o que foi decidido depois de ver os dados? Uma mudança planejada como contingência no protocolo só precisa ser registrada como acionada; as demais entram como emenda justificada <span class="co">[</span><span class="ot">@vandenakker2023increasing</span><span class="co">]</span>.</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## O pacote aberto {#sec-apb-pacote}</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>A lista de arquivos do pacote, com o item PRISMA de cada um, está na @sec-10-passos. Antes de depositar, confira:</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**README** descreve cada arquivo, a versão da revisão e a ordem para reproduzir, do arquivo de registros ao relatório.</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Fluxograma reproduzível**: as contagens publicadas saem das tabelas de registros e decisões incluídas no pacote.</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Código roda do zero** num ambiente limpo, com as versões dos pacotes usados na análise registradas junto dos *scripts* (@sec-10-passos); quem usa programas de apontar e clicar descreve todos os passos <span class="co">[</span><span class="ot">@page2021explanation, item 27</span><span class="co">]</span>.</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Tabela de conversões** acompanha os dados extraídos, com fórmula e pressupostos de cada efeito convertido (@sec-07-efeitos).</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Tabela-fonte da caixa de ferramentas** e a versão da regra de rótulos permitem refazer cada rótulo (@sec-10-painel).</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Prompts, saídas brutas e métricas de validação** estão presentes quando houve uso de IA (@sec-11-relato).</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Material protegido fica de fora**: exportações de bases bibliográficas costumam conter conteúdo licenciado, e as licenças devem ser lidas antes de compartilhar; no lugar dos resumos, publique identificadores e decisões <span class="co">[</span><span class="ot">@page2021explanation, item 27</span><span class="co">]</span>. PDFs dos estudos não entram no pacote.</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Dados pessoais** (de autores contatados, de participantes de validação) são removidos ou tratados conforme a LGPD <span class="co">[</span><span class="ot">@brasil2018lgpd</span><span class="co">]</span>.</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>**Identificador persistente** do depósito aparece no artigo, na síntese de evidências e em cada produto derivado (@sec-10-passos).</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Licenças e terceiros {#sec-apb-licencas}</span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>Três situações exigem cuidado. A primeira são os dados de terceiros: resumos e registros exportados de bases comerciais seguem a licença da base, não a da revisão <span class="co">[</span><span class="ot">@page2021explanation, item 27</span><span class="co">]</span>. A segunda é o envio de títulos, resumos e PDFs a provedores de IA: os termos de serviço podem permitir o uso para treino, e carregar texto protegido pode constituir reprodução, por isso os acordos de processamento e de confidencialidade são conferidos antes do uso e relatados <span class="co">[</span><span class="ot">@thomas2026raise3, p. 29; @holst2025prismatraice</span><span class="co">]</span>. A terceira é o material próprio da revisão (codebook, dados extraídos, código, tabela de achados): declare uma licença explícita no README de cada componente. A skill <span class="in">`revisao-sistematica`</span> adota MIT para o código e CC BY 4.0 para textos, modelos e codebooks (@sec-especificacao-contrato). Para reutilizar materiais didáticos do MAPE/IESP-UERJ ou modelos de terceiros, como o fluxograma PRISMA, siga a licença e a atribuição indicadas pela fonte <span class="co">[</span><span class="ot">@prisma2020flow</span><span class="co">]</span>.</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>