---
title: "Definiçao do protocolo inicial"
subtitle: "Aula 2"
date: 2026-04-10
---

## O que é um protocolo?

O protocolo é útil para evitar um selection bias dos estudos que serao incluídos na minha pesquisa. Isso envolve:

- Como eu vou buscar a literatura
- Como eu vou definir os critérios de inclusao (o que inclui, por exemplo, como eu faço pra avaliar a qualidade do estudo)
- Como eu vou extrair os estudos
- Como eu vou sintetizar os resultados

Pensando nessas regras, precisamos pensar no que precisa constar no protocolo. A ideia do PRISMA -- Preferred Reporting Items for  Systematic Reviews and Meta-Analysis.

## Tipos de pergunta de pesquisa


### O que estamos avaliando?

- Definir a intervençao (X) -- variável independente
- Definir o resultado (Y) -- variável dependente
- Definir os mecanismos (M) e moderadores (Z) que conectam X e Y (Por quê? Como?) e moderam o efeito (Para quem? Quando? Onde?), respectivamente

### Perguntas medianas melhoradas

- Quais políticas sao efetivas para a reduçao do abandono escolar? --- Programas de transferência de renda condicionada reduzem o abandono escolar?
- A implementaçao do reconhecimento facial possui quais efeitos? --- Políticas de reconhecimento facial aumentam o número de prisoes erradas?

## Teoria da mudança / teoria do desenho

A teoria da mudança ou teoria do desenho envolve pensar no modelo lógico que conecta a intervençao aos resultados. Quando pensamos em avaliacao de impacto, mesmo que uma revisao sistemática, é interessante pensar nos tipos de variáveis.

Ver códigos em R no OSF, que incluem, por exemplo, a criaçao de DAGs.

## Tipos de estruturas

Uma estrutura conhecida é a PICO, mas há várias (SPICE, SPIDER) etc, a partir das quais podemos derivar os termos de busca.

## PRISMA -- Checklist

## Pré-registro